autoload, "calps.i", calps_compatibility;
autoload, "calps.i", _ytriangulate, triangulate;
autoload, "calps.i", _yinterp_angles;
autoload, "calps.i", _ydet, _yplanar_params_from_pts;
autoload, "calps.i", _ycross_product_sign, _yin_triangle;
autoload, "calps.i", _ytriangle_interp, _ywrite_arc_grid;
autoload, "calps.i", _yin_box, _ylevel_short_dips;
autoload, "calps.i", _yll2utm, _yutm2ll;
autoload, "calps.i", calps_n88_interp_qfit2d, calps_n88_interp_spline2d;
autoload, "calps.i", _yset_intersect_long, _yset_intersect_double;
autoload, "calps.i", _ymergeuniq_L, _ymergeuniq_D;
autoload, "calps.i", get_pid;
autoload, "calps.i", profiler_init, profiler_reset, profiler_ticks;
