#!/bin/sh
#
#mkeidx: automatically make the master earl index
# ls *.tld | /opt/alps/lidar-processing/bin/efdb MM-DD-YY.idx
# 
# Original: Richard Mitchell.
#
# This program:
#
# 1) Determines the mission date 
# 2) Generates a sorted list of files in the "eaarl" subdir and
#    feeds those names to efdb which creates an "idx" file named
#    after the mission date.     

efdb="efdb"                   # this should work if pathing is setup
# efdb="/opt/eaarl/bin/efdb"  # else 
dir=`pwd`
name=`basename $dir`".idx"
echo $name
cd eaarl
# find . -name \*.tld | sed 's#./##'
find . -name \*.tld | sed 's#./##' | sort | $efdb $name
