#!/usr/bin/perl
# a wrapper for rsync.
# sets the most commonly used options (-Pav) and also the timeout value to
# 5 seconds.  The wrapper checks the return value.  If the return value
# indicates the transfer timed out or never started, then the rsync is
# re-issued.

$TIMEOUT = 3072;  # should be 30 according to man, but actual use returned this
$NOSTART = 7680;  # discovered through use.


######################################################################

use Getopt::Long;

undef $opt_help;     # quiet the warning message
undef $getopt;       # quiet the warning message

sub showusage {
  print <<EOF;

$0 [-[no]help] [-[no]tar] [-xyz] -[no]z] -[R]

-z    : use compression
-noz  : do NOT use compression

-tar  : rsync only .tar files, do NOT use compresssion unless -z
-notar: rsync everything but .tar files, use compression unless -noz

-xyz  : rsync only .xyz files

-alps : rsync only the alps and soxmap directories.

-n    : show the rsync command to use, but don't issue it.

-norsync: pass -n to rsync

The trajectories subdirectory is not synced.

[-nohelp]: better than nothing

EOF

# print out actual GetOptions() used if -nohelp is specified.
printf("\n%s\n", $options) if ( $opt_help == 0 );

  exit(0);
}

############################################################
# defaults are supplied in GetOptions itself
# use: perldoc Getopt::Long           # to get the manpage #

$options = <<END;
\$getopt = GetOptions (
  'help!'      => \\( \$opt_help = -1   ),  # use -nohelp to show this
  'myint:i'    => \\( \$myint    = -1   ),  # example optional int
  'myfloat=f'  => \\( \$myfloat  = 1.5  ),  # example floaat
  'mystr=s'    => \\( \$mystr    = "foo"),  # example string
  'verbose!'   => \\( \$verbose  = -1   ),  # example bool with negate option
  'tar!'       => \\( \$tar      = -1   ),  # tar / notar option
  'ash!'       => \\( \$ash      = -1   ),  # ash / noash option
  'xyz!'       => \\( \$xyz      = -1   ),  # xyz files
  'alps!'      => \\( \$alps     = -1   ),  # alps files
  'z!'         => \\( \$z        = -1   ),  # use -z in rsync
  'R!'         => \\( \$R        = -1   ),  # use -R in rsync
  'n!'         => \\( \$n        = -1   ),  # don't run, only show command to use'
  'norsync!'   => \\( \$norsync  = -1   ),  # pass -n to rsync
  'noperm!'    => \\( \$noperm   = -1   ),  # pass -noperms to rsync
);
&showusage() if (\$opt_help >= 0);
END

eval $options;
&showusage() if ($getopt == 0); # result is 1 if no errors

# printf("myint    = %d\n", $myint  ) if ( $myint  );
# printf("myfloat  = %f\n", $myfloat) if ( $myfloat);
# printf("magic    = %f\n", $magic  ) if ( $magic  );
# printf("mystr    = %s\n", $mystr  ) if ( $mystr  );
# printf("verbose  = not set\n"     ) if ( $verbose == -1 );
printf("verbose  = %2d\n", $verbose) if ( $verbose >=  0 );
printf("tar      = %2d\n", $tar    ) if ( $verbose >-  0 );
printf("ash      = %2d\n", $ash    ) if ( $verbose >-  0 );
printf("xyz      = %2d\n", $xyz    ) if ( $verbose >-  0 );
printf("alps     = %2d\n", $alps   ) if ( $verbose >-  0 );
printf("z        = %2d\n", $z      ) if ( $verbose >-  0 );
printf("R        = %2d\n", $R      ) if ( $verbose >-  0 );
printf("n        = %2d\n", $n      ) if ( $verbose >-  0 );
printf("norsync  = %2d\n", $norsync) if ( $verbose >-  0 );
printf("noperms  = %2d\n", $noperms) if ( $verbose >-  0 );

# exit(0);
######################################################################

$z = 1 if ( $z == -1 && $tar == 0 );

my $notraj   = "--exclude='**/trajectories/**' ";
my $notarstr = "--include='*/' --exclude='*.tar' $notraj --include='*' ";
my   $tarstr = "--include='*/' --include='*.tar' $notraj --exclude='*' ";
my   $ashstr = "--include='*/' --include='*.ash' $notraj --exclude='*' ";
my   $xyzstr = "--include='*/' --include='*.xyz' $notraj --exclude='*' ";
my   $alpstr = "--include='**/alps/**' --include='**/soxmap/**' --exclude='20*/' ";
my   $zstr   = "-z ";
my   $Rstr   = "-R ";
my   $nors   = "-n ";
my   $permstr= "--no-perms --modify-window=1 --no-owner ";

my $opt = "";
   $opt = $notarstr if ( $tar ==  0 );
   $opt =   $tarstr if ( $tar ==  1 );
   $opt =   $ashstr if ( $ash ==  1 );
   $opt =   $xyzstr if ( $xyz ==  1 );
   $opt =   $alpstr if ( $alps==  1 );
   $opt .=  $zstr   if ( $z   ==  1 );  # append these options if selected
   $opt .=  $Rstr   if ( $R   ==  1 );
   $opt =   $notraj if ( $opt eq "" );
   $opt .=  $nors   if ( $norsync == 1 );
   $opt .=  $permstr if ( $noperm == 1 );


$cmd = "rsync --timeout 20 -PHavmh $opt";
for ( $i=0; $i<=$#ARGV; ++$i) {
  if ( $ARGV[$i] =~ '`' ) {
    # printf("hit: %s\n", $ARGV[$i] );
    my ( $left, $right ) = split(/:/, $ARGV[$i]);
    $cmd .= "$left:'$right'";
  } else {
    $cmd .= $ARGV[$i];
  }
  $cmd .= " ";
  # printf("%d: %s\n", $i, $cmd );
}

# printf("%s#\n", $cmd);

$stat = $TIMEOUT;

while ( $stat == $TIMEOUT || $stat == $NOSTART) {
  system("echo $cmd");
  system("     $cmd") if ( $n == -1 );
  $stat = $?;
  printf("Status = %d\n", $stat);
  sleep(5)            if ( $n == -1 ); # Give things a chance to fix
}

exit(0);
