#!/usr/bin/perl
# 2004-09-03:  checksys - scans the network,
#              reports which systems are up,
#              and which should be shutdown.               rwm

# $Id$

# Adjust here for your network.
$NETWORK = "192.168.1",
$NETMASK = "255";

open(PING, "ping -b $NETWORK.$NETMASK|") || die("Unable to ping\n");

$done = 0;
while ( !$done && ($line = <PING>)) {
  @arr = split(/[ :]/, $line);
  @ip  = split(/\./, $arr[3]);
  $hosts[$ip[3]] = time();
  $count[$ip[3]]++;
  # printf("%s: %s\n", $hosts[$ip[3]], $ip[3]);
  $done = True if ( $count[$ip[3]] >= 2 );
}

$t = time();

open(HOSTS, "/etc/hosts") || die ("Unable to open /etc/hosts\n");
@hosttable = <HOSTS>;
close(HOSTS);

for ($i=1; $i<=255; ++$i) {
  if ( $hosts[$i] >0 ) {
    $ip = sprintf("^%s.%d ", $NETWORK, $i);
    @list = grep ( /$ip/, @hosttable);
    if ( $#list == 0 ) {    # we got one hit
      ($junk1, $name, $junk2) = split(/\s+/, $list[0], 3);
    } else {
      $name = "UnKnown";
    }
    

    SWITCH: for ($name) {
      ( /gps140/ || 
        /gps141/ ||
        /gps143/ ||
        /gps144/ ||
        /gps145/ ||
        /gps207/ ||
        /eaarl/  ||
        /cam1/
      ) && do {
         printf("%3d (%2d): %d  # %s\t",
           $i, $count[$i], $t-$hosts[$i], $name);
         printf("Shut down $name\n");
         last;
      };

      # This is duplicated so that it could just be commented out
      # and ignored.
      do {
         printf("%3d (%2d): %d  # %s\n",
           $i, $count[$i], $t-$hosts[$i], $name);
      };
    }
  }
}

exit
