require, "sel_file.i"


/* DOCUMENT rdashc

  Read and Ashtech "C" file.  These files are generated by the 
Ashtech software that B.J. Renolds uses.  Produces an
array of structures containing hours,mins,seconds, seconds-of-the-day
(sod), svs, pdop, lat,lon, alt, rms, and a data flag.


*/

 if ( is_void(data_path) ) {
   data_path = rdline(prompt="Enter data path:");  
 }

  ashfn = sel_file( path= data_path )(1);

f = open( ashfn );
ashc_header = "";

// Read the header stuff and display
 for (i=1; i<=5; i++ ) {
  s = rdline(f);
  write(format="%s", s);
  grow,ashc_header,s;
 }

 struct ASHC {
  float xrms; 
  float pdop;
  float secs;
  double lat;
  double  lon; 
  double alt;
  double sod;
  int  flag;
  int svs;
  int hrs;
  int mins;
};


 nn = 15;		// number of columns
 nl = 5000;		// lines in a block
 cnt = 0;
 s = array(string, nn, nl );
 write,format="\n", n;
 lat = [];
 lon = [];
 alt = [];
 flag = [];
 xrms = [];
 svs  = [];
 pdop  = [];
 hrs = [];
 mins = [];
 secs  = [];
 sod = [];
 while ( 1 ) {
   n = read(f, format="%s", s );
  cnt += (n/nn);
 tf = array(double,n/nn);
 ti = array(int, n/nn);
 sn = array(float, n/nn);
 a = array(float, n/nn);
 b = array(float, n/nn);
 c = array(float, n/nn);
 write,format="%d          \r",  cnt ;
  sread, s(7,  ), format="%f", tf
  grow, lat, tf

  l = where( s(8,) == "W" );
  sn(l) = -1.0;

  sread, s(9, ), format="%f", tf
  tf *= sn;
  grow, lon, tf

  sread, s(10, ), format="%f", tf
  grow, alt, tf
   
  sread, s(11, ), format="%f", tf
  grow, xrms, tf;

  sread, s(12, ), format="%d", ti
  grow, flag, ti;

  sread, s(4, ), format="%d", ti
  grow, svs, ti;

  sread, s(5, ), format="%f", tf
  grow, pdop, tf;

  sread, s(3, ), format="%f:%f:%f", a, b, c 
  grow, hrs, a;
  grow, mins, b;
  grow, secs, c; 
  if ( n < (nn*nl) ) {
     break;
  }
 } 
 sod =  hrs*3600.0 + mins * 60.0 + secs ;
 
  ashc = array( ASHC, dimsof( lat) (2));
  ashc.lat = lat;
  ashc.lon = lon;
  ashc.alt = alt;
  ashc.xrms = xrms;
  ashc.hrs  = hrs;
  ashc.mins = mins;
  ashc.secs = secs;
  ashc.pdop = pdop;
  ashc.sod = sod;
  ashc.svs = svs;

 write,format="\n", n
close,f

 write,format="You now have a new data structure named ASHC\n\
and a new array containing the data named ashc.  Type ASHC to\n\
see whats in the structure.\n\
Some usefule commands follow:\n\
plg, ashc.lat,ashc.lon          Plot lat/lon\n\
plg, ashc.sod                   Plot seconds of the day\n\
plg, ashc.xrms,ashc.sod         Plot rms errors vs seconds of the day\n\n", ""

